START TRANSACTION;

INSERT INTO country (name, code, capital, continent, flag_image) VALUES
('Afghanistan','AF','Kabul','Asia','https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg'),
('Albania','AL','Tirana','Europe','https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg'),
('Algeria','DZ','Algiers','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg'),
('Andorra','AD','Andorra la Vella','Europe','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg'),
('Angola','AO','Luanda','Africa','https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg'),
('Antigua and Barbuda','AG','St. John''s','North America','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg'),
('Argentina','AR','Buenos Aires','South America','https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg'),
('Armenia','AM','Yerevan','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg'),
('Australia','AU','Canberra','Oceania','https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg'),
('Austria','AT','Vienna','Europe','https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg'),
('Azerbaijan','AZ','Baku','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg'),
('Bahamas','BS','Nassau','North America','https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg'),
('Bahrain','BH','Manama','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg'),
('Bangladesh','BD','Dhaka','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg'),
('Barbados','BB','Bridgetown','North America','https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg'),
('Belarus','BY','Minsk','Europe','https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg'),
('Belgium','BE','Brussels','Europe','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Belgium_%28civil%29.svg'),
('Belize','BZ','Belmopan','North America','https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg'),
('Benin','BJ','Porto-Novo','Africa','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg'),
('Bhutan','BT','Thimphu','Asia','https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg'),
('Bolivia','BO','Sucre','South America','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg'),
('Bosnia and Herzegovina','BA','Sarajevo','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg'),
('Botswana','BW','Gaborone','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg'),
('Brazil','BR','Brasilia','South America','https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg'),
('Brunei','BN','Bandar Seri Begawan','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg'),
('Bulgaria','BG','Sofia','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg'),
('Burkina Faso','BF','Ouagadougou','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg'),
('Burundi','BI','Bujumbura','Africa','https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg'),
('Cambodia','KH','Phnom Penh','Asia','https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg'),
('Cameroon','CM','Yaounde','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg'),
('Canada','CA','Ottawa','North America','https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg'),
('Cape Verde','CV','Praia','Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg'),
('Central African Republic','CF','Bangui','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg'),
('Chad','TD','N''Djamena','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg'),
('Chile','CL','Santiago','South America','https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg'),
('China','CN','Beijing','Asia','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg'),
('Colombia','CO','Bogotá','South America','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg'),
('Comoros','KM','Moroni','Africa','https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg'),
('Democratic Republic of the Congo','CD','Kinshasa','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg'),
('Republic of Congo','CG','Brazzaville','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg'),
('Costa Rica','CR','San Jose','North America','https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg'),
('Croatia','HR','Zagreb','Europe','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg'),
('Cuba','CU','Havana','North America','https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg'),
('Cyprus','CY','Nicosia','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg'),
('Czech Republic','CZ','Prague','Europe','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg'),
('Denmark','DK','Copenhagen','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg'),
('Djibouti','DJ','Djibouti','Africa','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg'),
('Dominica','DM','Roseau','North America','https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg'),
('Dominican Republic','DO','Santo Domingo','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg'),
('Ecuador','EC','Quito','South America','https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg'),
('Egypt','EG','Cairo','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg'),
('El Salvador','SV','San Salvador','North America','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg'),
('Equatorial Guinea','GQ','Malabo','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg'),
('Eritrea','ER','Asmara','Africa','https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg'),
('Estonia','EE','Tallinn','Europe','https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg'),
('Eswatini', 'SZ', 'Mbabane', 'Africa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/125px-Flag_of_Eswatini.svg.png'),
('Ethiopia','ET','Addis Ababa','Africa','https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg'),
('Fiji','FJ','Suva','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg'),
('Finland','FI','Helsinki','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg'),
('France','FR','Paris','Europe','https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg'),
('Gabon','GA','Libreville','Africa','https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg'),
('The Gambia','GM','Banjul','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg'),
('Georgia','GE','Tbilisi','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg'),
('Germany','DE','Berlin','Europe','https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg'),
('Ghana','GH','Accra','Africa','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg'),
('Greece','GR','Athens','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg'),
('Greenland','GL','Nuuk','North America','https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/1280px-Flag_of_Greenland.svg.png'),
('Grenada','GD','St. George''s','North America','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg'),
('Guatemala','GT','Guatemala City','North America','https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg'),
('Guinea','GN','Conakry','Africa','https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg'),
('Guinea-Bissau','GW','Bissau','Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg'),
('Guyana','GY','Georgetown','South America','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg'),
('Haiti','HT','Port-au-Prince','North America','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg'),
('Honduras','HN','Tegucigalpa','North America','https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg'),
('Hungary','HU','Budapest','Europe','https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg'),
('Iceland','IS','Reykjavik','Europe','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg'),
('India','IN','New Delhi','Asia','https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg'),
('Indonesia','ID','Jakarta','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg'),
('Iran','IR','Tehran','Asia','https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg'),
('Iraq','IQ','Baghdad','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg'),
('Ireland','IE','Dublin','Europe','https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg'),
('Israel','IL','Jerusalem','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg'),
('Italy','IT','Rome','Europe','https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg'),
('Ivory Coast','CI','Yamoussoukro','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg'),
('Jamaica','JM','Kingston','North America','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg'),
('Japan','JP','Tokyo','Asia','https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg'),
('Jordan','JO','Amman','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg'),
('Kazakhstan','KZ','Astana','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg'),
('Kenya','KE','Nairobi','Africa','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg'),
('Kiribati','KI','Tarawa','Oceania','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg'),
('North Korea','KP','Pyongyang','Asia','https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg'),
('South Korea','KR','Seoul','Asia','https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg'),
('Kuwait','KW','Kuwait City','Asia','https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg'),
('Kyrgyzstan','KG','Bishkek','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg'),
('Laos','LA','Vientiane','Asia','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg'),
('Latvia','LV','Riga','Europe','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg'),
('Lebanon','LB','Beirut','Asia','https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg'),
('Lesotho','LS','Maseru','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg'),
('Liberia','LR','Monrovia','Africa','https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg'),
('Libya','LY','Tripolis','Africa','https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg'),
('Liechtenstein','LI','Vaduz','Europe','https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg'),
('Lithuania','LT','Vilnius','Europe','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg'),
('Luxembourg','LU','Luxembourg','Europe','https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg'),
('Madagascar','MG','Antananarivo','Africa','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg'),
('Malawi','MW','Lilongwe','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg'),
('Malaysia','MY','Kuala Lumpur','Asia','https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg'),
('Maldives','MV','Male','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg'),
('Mali','ML','Bamako','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg'),
('Malta','MT','Valletta','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg'),
('Marshall Islands','MH','Majuro','Oceania','https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg'),
('Mauritania','MR','Nouakchott','Africa','https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg'),
('Mauritius','MU','Port Louis','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg'),
('Mexico','MX','Ciudad de México','North America','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg'),
('Micronesia','FM','Palikir','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg'),
('Moldova','MD','Chisinau','Europe','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg'),
('Monaco','MC','Monaco','Europe','https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg'),
('Mongolia','MN','Ulan Bator','Asia','https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg'),
('Montenegro','ME','Podgorica','Europe','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg'),
('Morocco','MA','Rabat','Africa','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg'),
('Mozambique','MZ','Maputo','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg'),
('Myanmar','MM','Nay Pyi Taw','Asia','https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg'),
('Namibia','NA','Windhoek','Africa','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg'),
('Nauru','NR','Yaren','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg'),
('Nepal','NP','Kathmandu','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg'),
('Netherlands','NL','Amsterdam','Europe','https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg'),
('New Zealand','NZ','Wellington','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg'),
('Nicaragua','NI','Managua','North America','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg'),
('Niger','NE','Niamey','Africa','https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg'),
('Nigeria','NG','Abuja','Africa','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg'),
('North Macedonia','MK','Skopje','Europe','https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_Macedonia.svg'),
('Norway','NO','Oslo','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg'),
('Oman','OM','Muscat','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg'),
('Pakistan','PK','Islamabad','Asia','https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg'),
('Palau','PW','Melekeok','Oceania','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg'),
('Palestine','PS','East Jerusalem','Asia','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg'),
('Panama','PA','Panama City','North America','https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg'),
('Papua New Guinea','PG','Port Moresby','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg'),
('Paraguay','PY','Asuncion','South America','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg'),
('Peru','PE','Lima','South America','https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg'),
('Philippines','PH','Manila','Asia','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg'),
('Poland','PL','Warsaw','Europe','https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg'),
('Portugal','PT','Lisbon','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg'),
('Puerto Rico','PR','San Juan','North America','https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/255px-Flag_of_Puerto_Rico.svg.png'),
('Qatar','QA','Doha','Asia','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
('Romania','RO','Bucharest','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg'),
('Russia','RU','Moscow','Europe','https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg'),
('Rwanda','RW','Kigali','Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg'),
('Saint Kitts and Nevis','KN','Basseterre','North America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg'),
('Saint Lucia','LC','Castries','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg'),
('Saint Vincent and the Grenadines','VC','Kingstown','North America','https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg'),
('Samoa','WS','Apia','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg'),
('San Marino','SM','San Marino','Europe','https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg'),
('Sao Tome and Principe','ST','Sao Tome','Africa','https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe#/media/File:Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg'),
('Saudi Arabia','SA','Riyadh','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg'),
('Senegal','SN','Dakar','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg'),
('Serbia','RS','Belgrade','Europe','https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg'),
('Seychelles','SC','Victoria','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg'),
('Sierra Leone','SL','Freetown','Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg'),
('Singapore','SG','Singapur','Asia','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg'),
('Slovakia','SK','Bratislava','Europe','https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg'),
('Slovenia','SI','Ljubljana','Europe','https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg'),
('Solomon Islands','SB','Honiara','Oceania','https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg'),
('Somalia','SO','Mogadishu','Africa','https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg'),
('South Africa','ZA','Pretoria','Africa','https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg'),
('South Sudan','SS','Juba','Africa','https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg'),
('Spain','ES','Madrid','Europe','https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg'),
('Sri Lanka','LK','Colombo','Asia','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg'),
('Sudan','SD','Khartoum','Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg'),
('Suriname','SR','Paramaribo','South America','https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg'),
('Sweden','SE','Stockholm','Europe','https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg'),
('Switzerland','CH','Bern','Europe','https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg'),
('Syria','SY','Damascus','Asia','https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg'),
('Taiwan','TW','Taipei','Asia','https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/150px-Flag_of_the_Republic_of_China.svg.png'),
('Tajikistan','TJ','Dushanbe','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg'),
('Tanzania','TZ','Dodoma','Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg'),
('Thailand','TH','Bangkok','Asia','https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg'),
('Togo','TG','Lome','Africa','https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg'),
('Tonga','TO','Nuku''alofa','Oceania','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg'),
('Trinidad and Tobago','TT','Port of Spain','South America','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg'),
('Tunisia','TN','Tunis','Africa','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg'),
('Turkey','TR','Ankara','Asia','https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg'),
('Turkmenistan','TM','Ashgabat','Asia','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg'),
('Tuvalu','TV','Funafuti','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg'),
('Uganda','UG','Kampala','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg'),
('Ukraine','UA','Kyiv','Europe','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg'),
('United Arab Emirates','AE','Abu Dhabi','Asia','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg'),
('United Kingdom','GB','London','Europe','https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg'),
('United States','US','Washington','North America','https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg'),
('Uruguay','UY','Montevideo','South America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg'),
('Uzbekistan','UZ','Tashkent','Asia','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg'),
('Vanuatu','VU','Port Vila','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg'),
('Vatican City','VA','Vatican City','Europe','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Flag_of_Vatican_City_%282023%E2%80%93present%29.svg/1280px-Flag_of_Vatican_City_%282023%E2%80%93present%29.svg.png'),
('Venezuela','VE','Caracas','South America','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg'),
('Vietnam','VN','Hanoi','Asia','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg'),
('Yemen','YE','Sanaa','Asia','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg'),
('Zambia','ZM','Lusaka','Africa','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg'),
('Zimbabwe','ZW','Harare','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg');

COMMIT;