# datasource connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/Flag_Guesser
spring.datasource.name=Flag_Guesser
spring.datasource.username=postgres
spring.datasource.password=postgres1