START TRANSACTION;

INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Afghanistan','AF','Kabul','Asia','https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Albania','AL','Tirana','Europe','https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Algeria','DZ','Algiers','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Andorra','AD','Andorra la Vella','Europe','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Angola','AO','Luanda','Africa','https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Antigua and Barbuda','AG','St. John''s','North America','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Argentina','AR','Buenos Aires','South America','https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Armenia','AM','Yerevan','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Australia','AU','Canberra','Oceania','https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Austria','AT','Vienna','Europe','https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Azerbaijan','AZ','Baku','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bahamas','BS','Nassau','North America','https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bahrain','BH','Manama','Asia','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bangladesh','BD','Dhaka','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Barbados','BB','Bridgetown','North America','https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Belarus','BY','Minsk','Europe','https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Belgium','BE','Brussels','Europe','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Belgium_%28civil%29.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Belize','BZ','Belmopan','North America','https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Benin','BJ','Porto-Novo','Africa','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bhutan','BT','Thimphu','Asia','https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bolivia','BO','Sucre','South America','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bosnia and Herzegovina','BA','Sarajevo','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Botswana','BW','Gaborone','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Brazil','BR','Brasilia','South America','https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Brunei','BN','Bandar Seri Begawan','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Bulgaria','BG','Sofia','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Burkina Faso','BF','Ouagadougou','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Burundi','BI','Bujumbura','Africa','https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Cambodia','KH','Phnom Penh','Asia','https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Cameroon','CM','Yaounde','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Canada','CA','Ottawa','North America','https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Cape Verde','CV','Praia','Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Central African Republic','CF','Bangui','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Chad','TD','N''Djamena','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Chile','CL','Santiago','South America','https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('China','CN','Beijing','Asia','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Colombia','CO','Bogotá','South America','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Comoros','KM','Moroni','Africa','https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Democratic Republic of the Congo','CD','Kinshasa','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Republic of Congo','CG','Brazzaville','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Costa Rica','CR','San Jose','North America','https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Croatia','HR','Zagreb','Europe','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Cuba','CU','Havana','North America','https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Cyprus','CY','Nicosia','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Czech Republic','CZ','Prague','Europe','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Denmark','DK','Copenhagen','Europe','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Djibouti','DJ','Djibouti','Africa','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Dominica','DM','Roseau','North America','https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Dominican Republic','DO','Santo Domingo','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ecuador','EC','Quito','South America','https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Egypt','EG','Cairo','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('El Salvador','SV','San Salvador','North America','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Equatorial Guinea','GQ','Malabo','Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Eritrea','ER','Asmara','Africa','https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Estonia','EE','Tallinn','Europe','https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Eswatini', 'SZ', 'Mbabane', 'Africa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/125px-Flag_of_Eswatini.svg.png');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ethiopia','ET','Addis Ababa','Africa','https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Fiji','FJ','Suva','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Finland','FI','Helsinki','Europe','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('France','FR','Paris','Europe','https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Gabon','GA','Libreville','Africa','https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('The Gambia','GM','Banjul','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Georgia','GE','Tbilisi','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Germany','DE','Berlin','Europe','https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ghana','GH','Accra','Africa','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Greece','GR','Athens','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Greenland','GL','Nuuk','North America','https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/1280px-Flag_of_Greenland.svg.png');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Grenada','GD','St. George''s','North America','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Guatemala','GT','Guatemala City','North America','https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Guinea','GN','Conakry','Africa','https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Guinea-Bissau','GW','Bissau','Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Guyana','GY','Georgetown','South America','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Haiti','HT','Port-au-Prince','North America','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Honduras','HN','Tegucigalpa','North America','https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Hungary','HU','Budapest','Europe','https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Iceland','IS','Reykjavik','Europe','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('India','IN','New Delhi','Asia','https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Indonesia','ID','Jakarta','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Iran','IR','Tehran','Asia','https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Iraq','IQ','Baghdad','Asia','https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ireland','IE','Dublin','Europe','https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Israel','IL','Jerusalem','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Italy','IT','Rome','Europe','https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ivory Coast','CI','Yamoussoukro','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Jamaica','JM','Kingston','North America','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Japan','JP','Tokyo','Asia','https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Jordan','JO','Amman','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Kazakhstan','KZ','Astana','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Kenya','KE','Nairobi','Africa','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Kiribati','KI','Tarawa','Oceania','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('North Korea','KP','Pyongyang','Asia','https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('South Korea','KR','Seoul','Asia','https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Kuwait','KW','Kuwait City','Asia','https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Kyrgyzstan','KG','Bishkek','Asia','https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Laos','LA','Vientiane','Asia','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Latvia','LV','Riga','Europe','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Lebanon','LB','Beirut','Asia','https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Lesotho','LS','Maseru','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Liberia','LR','Monrovia','Africa','https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Libya','LY','Tripolis','Africa','https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Liechtenstein','LI','Vaduz','Europe','https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Lithuania','LT','Vilnius','Europe','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Luxembourg','LU','Luxembourg','Europe','https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Madagascar','MG','Antananarivo','Africa','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Malawi','MW','Lilongwe','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Malaysia','MY','Kuala Lumpur','Asia','https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Maldives','MV','Male','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mali','ML','Bamako','Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Malta','MT','Valletta','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Marshall Islands','MH','Majuro','Oceania','https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mauritania','MR','Nouakchott','Africa','https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mauritius','MU','Port Louis','Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mexico','MX','Ciudad de México','North America','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Micronesia','FM','Palikir','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Moldova','MD','Chisinau','Europe','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Monaco','MC','Monaco','Europe','https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mongolia','MN','Ulan Bator','Asia','https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Montenegro','ME','Podgorica','Europe','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Morocco','MA','Rabat','Africa','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Mozambique','MZ','Maputo','Africa','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Myanmar','MM','Nay Pyi Taw','Asia','https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Namibia','NA','Windhoek','Africa','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Nauru','NR','Yaren','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Nepal','NP','Kathmandu','Asia','https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Netherlands','NL','Amsterdam','Europe','https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('New Zealand','NZ','Wellington','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Nicaragua','NI','Managua','North America','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Niger','NE','Niamey','Africa','https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Nigeria','NG','Abuja','Africa','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('North Macedonia','MK','Skopje','Europe','https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_Macedonia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Norway','NO','Oslo','Europe','https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Oman','OM','Muscat','Asia','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Pakistan','PK','Islamabad','Asia','https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Palau','PW','Melekeok','Oceania','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Palestine','PS','East Jerusalem','Asia','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Panama','PA','Panama City','North America','https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Papua New Guinea','PG','Port Moresby','Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Paraguay','PY','Asuncion','South America','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Peru','PE','Lima','South America','https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Philippines','PH','Manila','Asia','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Poland','PL','Warsaw','Europe','https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Portugal','PT','Lisbon','Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Puerto Rico','PR','San Juan','North America','https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/255px-Flag_of_Puerto_Rico.svg.png');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Qatar','QA','Doha','Asia','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Romania','RO','Bucharest','Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Russia','RU','Moscow','Europe','https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Rwanda','RW','Kigali','Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Saint Kitts and Nevis','KN','Basseterre','North America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Saint Lucia','LC','Castries','North America','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Saint Vincent and the Grenadines','VC','Kingstown','North America','https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Samoa','WS','Apia','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('San Marino','SM','San Marino','Europe','https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Sao Tome and Principe','ST','Sao Tome','Africa','https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe#/media/File:Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Saudi Arabia','SA','Riyadh','Asia','https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Senegal','SN','Dakar','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Serbia','RS','Belgrade','Europe','https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Seychelles','SC','Victoria','Africa','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Sierra Leone','SL','Freetown','Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Singapore','SG','Singapur','Asia','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Slovakia','SK','Bratislava','Europe','https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Slovenia','SI','Ljubljana','Europe','https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Solomon Islands','SB','Honiara','Oceania','https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Somalia','SO','Mogadishu','Africa','https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('South Africa','ZA','Pretoria','Africa','https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('South Sudan','SS','Juba','Africa','https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Spain','ES','Madrid','Europe','https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Sri Lanka','LK','Colombo','Asia','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Sudan','SD','Khartoum','Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Suriname','SR','Paramaribo','South America','https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Sweden','SE','Stockholm','Europe','https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Switzerland','CH','Bern','Europe','https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Syria','SY','Damascus','Asia','https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Taiwan','TW','Taipei','Asia','https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/150px-Flag_of_the_Republic_of_China.svg.png');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Tajikistan','TJ','Dushanbe','Asia','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Tanzania','TZ','Dodoma','Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Thailand','TH','Bangkok','Asia','https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Togo','TG','Lome','Africa','https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Tonga','TO','Nuku''alofa','Oceania','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Trinidad and Tobago','TT','Port of Spain','South America','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Tunisia','TN','Tunis','Africa','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Turkey','TR','Ankara','Asia','https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Turkmenistan','TM','Ashgabat','Asia','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Tuvalu','TV','Funafuti','Oceania','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Uganda','UG','Kampala','Africa','https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Ukraine','UA','Kyiv','Europe','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('United Arab Emirates','AE','Abu Dhabi','Asia','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('United Kingdom','GB','London','Europe','https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('United States','US','Washington','North America','https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Uruguay','UY','Montevideo','South America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Uzbekistan','UZ','Tashkent','Asia','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Vanuatu','VU','Port Vila','Oceania','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Vatican City','VA','Vatican City','Europe','https://en.wikipedia.org/wiki/Vatican_City#/media/File:Flag_of_the_Vatican_City_(2023%E2%80%93present).svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Venezuela','VE','Caracas','South America','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Vietnam','VN','Hanoi','Asia','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Yemen','YE','Sanaa','Asia','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Zambia','ZM','Lusaka','Africa','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg');
INSERT INTO country (name, code, capital, continent, flag_image) VALUES ('Zimbabwe','ZW','Harare','Africa','https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg');

COMMIT;
